# Generated by Django 5.0.1 on 2026-01-14 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='이력서 제목')),
                ('url', models.TextField(blank=True, null=True, verbose_name='이력서 URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일자')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
            ],
            options={
                'verbose_name': '이력서',
                'verbose_name_plural': '이력서 목록',
                'db_table': 'resume',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeMatching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='매칭률')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='분석 내용')),
                ('question', models.TextField(blank=True, null=True, verbose_name='면접 질문')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일자')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
            ],
            options={
                'verbose_name': '이력서 매칭',
                'verbose_name_plural': '이력서 매칭 목록',
                'db_table': 'resume_matching',
            },
        ),
        migrations.CreateModel(
            name='ResumeStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '이력서-기술 연결',
                'verbose_name_plural': '이력서-기술 연결 목록',
                'db_table': 'resume_stack',
            },
        ),
    ]
