# Generated by Django 5.0.1 on 2026-01-14 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0002_initial'),
        ('resumes', '0001_initial'),
        ('trends', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AddField(
            model_name='resumematching',
            name='job_posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_matchings', to='jobs.jobposting', verbose_name='채용 공고'),
        ),
        migrations.AddField(
            model_name='resumematching',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_matchings', to='resumes.resume', verbose_name='이력서'),
        ),
        migrations.AddField(
            model_name='resumestack',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_stacks', to='resumes.resume', verbose_name='이력서'),
        ),
        migrations.AddField(
            model_name='resumestack',
            name='tech_stack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='trends.techstack', verbose_name='기술 스택'),
        ),
    ]
