# Generated by Django 5.0.1 on 2026-01-19 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumematching',
            name='updated_at',
        ),
    ]
