# Generated by Django 5.0.1 on 2026-01-20 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_remove_resumematching_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=256, verbose_name='프로젝트명')),
                ('context', models.TextField(verbose_name='프로젝트 요약')),
                ('details', models.TextField(verbose_name='프로젝트 설명')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_experiences', to='resumes.resume', verbose_name='이력서')),
            ],
            options={
                'verbose_name': '프로젝트 경험',
                'verbose_name_plural': '프로젝트 경험 목록',
                'db_table': 'project_experience',
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=256, verbose_name='회사명')),
                ('details', models.TextField(verbose_name='업무 설명')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='resumes.resume', verbose_name='이력서')),
            ],
            options={
                'verbose_name': '직무 경험',
                'verbose_name_plural': '직무 경험 목록',
                'db_table': 'work_experience',
            },
        ),
    ]
