# Generated by Django 5.0.1 on 2026-01-20 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0004_projectexperience_workexperience'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeExtractedStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_tools', models.JSONField(default=list, verbose_name='기술 스택')),
                ('methodologies', models.JSONField(default=list, verbose_name='방법론')),
                ('others', models.JSONField(default=list, verbose_name='기타')),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_stack', to='resumes.resume', verbose_name='이력서')),
            ],
            options={
                'verbose_name': '이력서 추출 스택',
                'verbose_name_plural': '이력서 추출 스택 목록',
                'db_table': 'resume_extracted_stack',
            },
        ),
    ]
