# Generated by Django 5.0.1 on 2026-01-21 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_jobpostingstack_unique_together'),
        ('resumes', '0005_resumeextractedstack'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resumematching',
            unique_together={('job_posting', 'resume')},
        ),
        migrations.RemoveField(
            model_name='resumematching',
            name='score',
        ),
    ]
