# Generated by Django 5.0.1 on 2026-01-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0006_alter_resumematching_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumematching',
            name='feedback',
        ),
        migrations.AddField(
            model_name='resumematching',
            name='negative_feedback',
            field=models.TextField(blank=True, null=True, verbose_name='부정적 분석'),
        ),
        migrations.AddField(
            model_name='resumematching',
            name='positive_feedback',
            field=models.TextField(blank=True, null=True, verbose_name='긍정적 분석'),
        ),
    ]
