# Generated by Django 5.0.1 on 2026-01-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0007_remove_resumematching_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumematching',
            name='enhancements_feedback',
            field=models.TextField(blank=True, null=True, verbose_name='보완할 점 분석'),
        ),
    ]
