# Generated by Django 5.0.14 on 2026-01-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0008_resumematching_enhancements_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumematching',
            name='answer',
            field=models.TextField(blank=True, null=True, verbose_name='모범 답변'),
        ),
    ]
