# Generated by Django 5.0.1 on 2026-01-14 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stack_count', models.BigIntegerField(default=0, verbose_name='게시글 언급량')),
                ('url', models.TextField(verbose_name='게시글 URL')),
                ('source', models.TextField(verbose_name='게시글 출처')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일자')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
            ],
            options={
                'verbose_name': '게시글',
                'verbose_name_plural': '게시글 목록',
                'db_table': 'article',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='카테고리명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일자')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
            ],
            options={
                'verbose_name': '카테고리',
                'verbose_name_plural': '카테고리 목록',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='TechBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
            ],
            options={
                'verbose_name': '기술 즐겨찾기',
                'verbose_name_plural': '기술 즐겨찾기 목록',
                'db_table': 'tech_bookmark',
            },
        ),
        migrations.CreateModel(
            name='TechStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='기술명')),
                ('logo', models.TextField(blank=True, null=True, verbose_name='기술 로고')),
                ('docs_url', models.TextField(blank=True, null=True, verbose_name='문서 URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일자')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
            ],
            options={
                'verbose_name': '기술 스택',
                'verbose_name_plural': '기술 스택 목록',
                'db_table': 'tech_stack',
            },
        ),
        migrations.CreateModel(
            name='TechTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trend_from', models.CharField(max_length=255, verbose_name='트렌드 출처 (키워드)')),
                ('mention_count', models.BigIntegerField(default=0, verbose_name='언급 수')),
                ('change_rate', models.FloatField(default=0.0, verbose_name='전주 대비 증가율')),
                ('reference_date', models.DateField(verbose_name='기준 날짜')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일자')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
            ],
            options={
                'verbose_name': '기술 트렌드',
                'verbose_name_plural': '기술 트렌드 목록',
                'db_table': 'tech_trend',
                'ordering': ['-reference_date', '-mention_count'],
            },
        ),
        migrations.CreateModel(
            name='ArticleStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='게시글 스택 언급량')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일자')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_stacks', to='trends.article', verbose_name='게시글')),
            ],
            options={
                'verbose_name': '게시글-기술 연결',
                'verbose_name_plural': '게시글-기술 연결 목록',
                'db_table': 'article_stack',
            },
        ),
        migrations.CreateModel(
            name='CategoryTech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_relations', to='trends.category', verbose_name='카테고리')),
            ],
            options={
                'verbose_name': '카테고리-기술 연결',
                'verbose_name_plural': '카테고리-기술 연결 목록',
                'db_table': 'category_tech',
            },
        ),
    ]
