# Generated by Django 5.0.1 on 2026-01-14 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trends', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='techbookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_bookmarks', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AddField(
            model_name='techbookmark',
            name='tech_stack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='trends.techstack', verbose_name='기술 스택'),
        ),
        migrations.AddField(
            model_name='categorytech',
            name='tech_stack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_relations', to='trends.techstack', verbose_name='기술 스택'),
        ),
        migrations.AddField(
            model_name='articlestack',
            name='tech_stack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='trends.techstack', verbose_name='기술 스택'),
        ),
        migrations.AddField(
            model_name='techtrend',
            name='tech_stack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trends', to='trends.techstack', verbose_name='기술 스택'),
        ),
        migrations.AlterUniqueTogether(
            name='techbookmark',
            unique_together={('user', 'tech_stack')},
        ),
        migrations.AlterUniqueTogether(
            name='categorytech',
            unique_together={('category', 'tech_stack')},
        ),
    ]
