# Generated by Django 5.0.1 on 2026-01-15 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techbookmark',
            name='is_deleted',
        ),
    ]
