# Generated by Django 5.0.1 on 2026-01-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0003_remove_techbookmark_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.TextField(unique=True, verbose_name='게시글 URL'),
        ),
        migrations.AlterUniqueTogether(
            name='articlestack',
            unique_together={('article', 'tech_stack')},
        ),
    ]
