# Generated by Django 5.0.1 on 2026-01-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0003_remove_techbookmark_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='techstack',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='기술 설명'),
        ),
    ]
