# Generated by Django 5.0.1 on 2026-01-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0004_alter_article_url_alter_articlestack_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='view_count',
            field=models.BigIntegerField(default=0, verbose_name='조회수'),
        ),
    ]
