# Generated by Django 5.0.1 on 2026-01-20 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0004_techstack_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechStackRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('synergy_with', '시너지 관계'), ('required_infra', '필수 인프라'), ('alternative', '대체 기술'), ('parent', '부모 기술'), ('child', '자식 기술')], max_length=50, verbose_name='관계 유형')),
                ('weight', models.FloatField(default=1.0, help_text='관계의 강도 (0.0 ~ 1.0)', verbose_name='관계 강도')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일자')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
                ('from_tech_stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='trends.techstack', verbose_name='출발 기술 스택')),
                ('to_tech_stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='trends.techstack', verbose_name='도착 기술 스택')),
            ],
            options={
                'verbose_name': '기술 스택 관계',
                'verbose_name_plural': '기술 스택 관계 목록',
                'db_table': 'tech_stack_relationship',
                'indexes': [models.Index(fields=['from_tech_stack', 'relationship_type'], name='tech_stack__from_te_d9284d_idx'), models.Index(fields=['to_tech_stack', 'relationship_type'], name='tech_stack__to_tech_52cf9f_idx')],
                'unique_together': {('from_tech_stack', 'to_tech_stack', 'relationship_type')},
            },
        ),
    ]
