# Generated by Django 5.0.1 on 2026-01-21 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0005_techstackrelationship'),
    ]

    operations = [
        # article_stack_count는 0006_remove_article_stack_count_and_more.py에서 이미 추가됨
        migrations.AddField(
            model_name='techstack',
            name='job_stack_count',
            field=models.BigIntegerField(default=0, verbose_name='채용공고 스택 언급량'),
        ),
    ]
