# Generated by Django 5.0.1 on 2026-01-22 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0005_article_view_count'),
        ('trends', '0005_techstackrelationship'),
    ]

    operations = [
    ]
