# Generated by Django 5.0.1 on 2026-01-21 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0005_techstackrelationship'),
        ('trends', '0006_techstack_article_stack_count_and_more'),
    ]

    operations = [
    ]
