# Generated by Django 5.0.1 on 2026-01-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0006_merge_20260122_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='stack_count',
        ),
        migrations.RemoveField(
            model_name='articlestack',
            name='count',
        ),
        migrations.AddField(
            model_name='techstack',
            name='article_stack_count',
            field=models.BigIntegerField(default=0, verbose_name='게시글 스택 언급량'),
        ),
    ]
