# Generated by Django 5.0.1 on 2026-01-22 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0006_techstack_article_stack_count_and_more'),
        ('trends', '0007_merge_20260121_2111'),
    ]

    operations = [
    ]
