# Generated by Django 5.0.1 on 2026-01-22 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0007_remove_article_stack_count_remove_articlestack_count_and_more'),
        ('trends', '0008_merge_20260122_0330'),
    ]

    operations = [
    ]
