# Generated by Django 5.0.14 on 2026-01-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0009_merge_20260122_2357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='techtrend',
            options={'ordering': ['-reference_date', '-job_mention_count'], 'verbose_name': '기술 트렌드', 'verbose_name_plural': '기술 트렌드 목록'},
        ),
        migrations.RemoveField(
            model_name='techtrend',
            name='change_rate',
        ),
        migrations.RemoveField(
            model_name='techtrend',
            name='mention_count',
        ),
        migrations.RemoveField(
            model_name='techtrend',
            name='trend_from',
        ),
        migrations.AddField(
            model_name='techtrend',
            name='job_change_rate',
            field=models.FloatField(default=0.0, verbose_name='전주 대비 채용공고 증가율'),
        ),
        migrations.AddField(
            model_name='techtrend',
            name='job_mention_count',
            field=models.BigIntegerField(default=0, verbose_name='채용공고 언급 수'),
        ),
        migrations.AddIndex(
            model_name='techtrend',
            index=models.Index(fields=['reference_date'], name='tech_trend_referen_8c78b9_idx'),
        ),
        migrations.AddIndex(
            model_name='techtrend',
            index=models.Index(fields=['tech_stack', 'reference_date'], name='tech_trend_tech_st_faccf4_idx'),
        ),
        migrations.AddConstraint(
            model_name='techtrend',
            constraint=models.UniqueConstraint(fields=('tech_stack', 'reference_date'), name='unique_daily_trend_per_stack'),
        ),
    ]
