# Generated by Django 5.0.14 on 2026-01-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0010_alter_techtrend_options_remove_techtrend_change_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='techtrend',
            name='article_mention_count',
            field=models.BigIntegerField(default=0, verbose_name='게시글 언급 수'),
        ),
        migrations.AddField(
            model_name='techtrend',
            name='article_change_rate',
            field=models.FloatField(default=0.0, verbose_name='전주 대비 게시글 증가율'),
        ),
    ]
