# Generated by Django 5.0.1 on 2026-01-14 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='기업명')),
                ('logo_url', models.TextField(blank=True, null=True, verbose_name='로고 URL')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='기업 주소')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='위도')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='경도')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일자')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
            ],
            options={
                'verbose_name': '기업',
                'verbose_name_plural': '기업 목록',
                'db_table': 'corp',
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(verbose_name='채용 공고 URL')),
                ('title', models.TextField(blank=True, null=True, verbose_name='채용 공고 제목')),
                ('description', models.TextField(blank=True, null=True, verbose_name='직무 설명')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='마감일')),
                ('career', models.CharField(blank=True, max_length=255, null=True, verbose_name='경력')),
                ('stack_count', models.BigIntegerField(default=0, verbose_name='채용 공고 스택 수')),
                ('posting_number', models.BigIntegerField(blank=True, null=True, verbose_name='채용 공고 번호')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일자')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
            ],
            options={
                'verbose_name': '채용 공고',
                'verbose_name_plural': '채용 공고 목록',
                'db_table': 'job_posting',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobPostingStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_stack_count', models.BigIntegerField(default=0, verbose_name='채용공고 스택 언급량')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일자')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
            ],
            options={
                'verbose_name': '채용 공고-기술 연결',
                'verbose_name_plural': '채용 공고-기술 연결 목록',
                'db_table': 'job_posting_stack',
            },
        ),
        migrations.CreateModel(
            name='CorpBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
                ('corp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='jobs.corp', verbose_name='기업')),
            ],
            options={
                'verbose_name': '기업 즐겨찾기',
                'verbose_name_plural': '기업 즐겨찾기 목록',
                'db_table': 'corp_bookmark',
            },
        ),
    ]
