# Generated by Django 5.0.1 on 2026-01-14 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('trends', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='corpbookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corp_bookmarks', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='corp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to='jobs.corp', verbose_name='기업'),
        ),
        migrations.AddField(
            model_name='jobpostingstack',
            name='job_posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_stacks', to='jobs.jobposting', verbose_name='채용 공고'),
        ),
        migrations.AddField(
            model_name='jobpostingstack',
            name='tech_stack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to='trends.techstack', verbose_name='기술 스택'),
        ),
        migrations.AlterUniqueTogether(
            name='corpbookmark',
            unique_together={('user', 'corp')},
        ),
    ]
