# Generated by Django 5.0.1 on 2026-01-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposting',
            name='stack_count',
        ),
        migrations.AlterField(
            model_name='jobpostingstack',
            name='job_stack_count',
            field=models.BigIntegerField(default=0, null=True, verbose_name='채용공고 스택 언급량'),
        ),
    ]
