# Generated by Django 5.0.1 on 2026-01-20 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_remove_jobpostingstack_job_stack_count'),
        ('trends', '0003_remove_techbookmark_is_deleted'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobpostingstack',
            unique_together={('job_posting', 'tech_stack')},
        ),
    ]
