# Generated by Django 5.0.14 on 2026-01-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_jobpostingstack_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='corp',
            name='region_city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='시/도'),
        ),
        migrations.AddField(
            model_name='corp',
            name='region_district',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='구/군'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='max_career',
            field=models.IntegerField(default=0, verbose_name='최대 경력(년)'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='min_career',
            field=models.IntegerField(default=0, verbose_name='최소 경력(년)'),
        ),
    ]
