"""
Django management command to categorize existing TechStack objects into predefined categories.

This command performs the following actions:
1. Defines a comprehensive mapping of technology names to a list of categories.
2. Ensures the 8 target categories (Frontend, Backend, AI & Data, DevOps, Embedding, Game, Security, etc) exist in the database, creating them if necessary.
3. Clears all existing TechStack-Category relationships to ensure a fresh start.
4. Iterates through all TechStack objects in the database.
5. For each TechStack, it looks up its categories in the predefined map and creates the corresponding CategoryTech relationships.
"""
from django.core.management.base import BaseCommand
from django.db import transaction
from apps.trends.models import TechStack, Category, CategoryTech

# A comprehensive map of technology names to their categories based on established rules.
# Rules: Role-based (Language, Framework, Platform), Dependency-informed, Job-market perception.
# Categories: Frontend, Backend, AI & Data, DevOps, Embedding, Game, Security, etc
TECH_TO_CATEGORIES = {
    # Languages
    'Python': ['Backend', 'AI & Data', 'DevOps'],
    'Java': ['Backend', 'AI & Data', 'Game'],
    'Java 8': ['Backend', 'AI & Data', 'Game'],
    'Java EE': ['Backend'],
    'JavaScript': ['Frontend', 'Backend'],
    'TypeScript': ['Frontend', 'Backend'],
    'C++': ['Backend', 'Game', 'Embedding'],
    'C#': ['Backend', 'Game'],
    'C lang': ['Backend', 'Game', 'Embedding'],
    'Go': ['Backend', 'DevOps'],
    'Golang': ['Backend', 'DevOps'],
    'Rust': ['Backend', 'DevOps', 'Game', 'Embedding'],
    'Swift': ['Frontend', 'Game'], # Primarily for iOS/macOS apps
    'Kotlin': ['Backend', 'Game'], # Primarily for Android and backend
    'Ruby': ['Backend'],
    'PHP': ['Backend'],
    'Dart': ['Frontend', 'Game'], # For Flutter
    'Scala': ['Backend', 'AI & Data'],
    'R Language': ['AI & Data'],
    'Shell': ['DevOps'],
    'GNU Bash': ['DevOps'],
    'PowerShell': ['DevOps'],
    'Groovy': ['DevOps', 'Backend'], # Jenkins, Gradle, Spring
    'Elixir': ['Backend'],
    'Clojure': ['Backend'],
    'ClojureScript': ['Frontend'],
    'Haskell': ['Backend'],
    'Perl': ['Backend', 'DevOps'],
    'Objective-C': ['Frontend'], # Legacy Apple development
    'Lua': ['Game', 'Embedding'],
    'Assembly Language': ['Embedding', 'Game'],
    'F#': ['Backend', 'AI & Data'],
    'Julia': ['AI & Data'],
    'Elm': ['Frontend'],
    'Crystal': ['Backend'],
    'Hack': ['Backend'], # From Facebook
    'D': ['Backend', 'Game'],
    'Smalltalk': ['Backend'],
    'Common Lisp': ['AI & Data', 'Backend'],
    'OCaml': ['Backend'],
    'Delphi': ['Backend'], # Legacy
    'Visual Basic': ['Backend'], # Legacy
    'PureBasic': ['Game'],
    'HTML5': ['Frontend'],
    'CSS 3': ['Frontend'],
    'SQL': ['Backend', 'AI & Data'],
    'ES6': ['Frontend', 'Backend'],

    # Frontend Frameworks & Libraries
    'React': ['Frontend'],
    'Angular': ['Frontend'],
    'AngularJS': ['Frontend'], # Legacy
    'Vue.js': ['Frontend'],
    'Svelte': ['Frontend'],
    'jQuery': ['Frontend'],
    'jQuery UI': ['Frontend'],
    'jQuery Mobile': ['Frontend'],
    'Next.js': ['Frontend', 'Backend'], # Full-stack
    'Nuxt.js': ['Frontend', 'Backend'], # Full-stack
    'Gatsby': ['Frontend'],
    'Ember.js': ['Frontend'],
    'Backbone.js': ['Frontend'],
    'Preact': ['Frontend'],
    # 'SolidJS': [], # Not in list, but would be Frontend
    # 'Lit': [], # Not in list, but would be Frontend
    'React Native': ['Frontend', 'Game'], # Mobile Apps
    'Flutter': ['Frontend', 'Game'],
    'Ionic': ['Frontend', 'Game'],
    'Xamarin': ['Frontend', 'Game'],
    'Xamarin Forms': ['Frontend', 'Game'],
    'NativeScript': ['Frontend', 'Game'],
    'Expo': ['Frontend', 'Game'],
    'SwiftUI': ['Frontend'],
    'Redux': ['Frontend'],
    'redux-thunk': ['Frontend'],
    'redux-saga': ['Frontend'],
    'reselect': ['Frontend'],
    'MobX': ['Frontend'],
    'vuex': ['Frontend'],
    'React Router': ['Frontend'],
    'Vue Router': ['Frontend'],
    'styled-components': ['Frontend'],
    'Emotion': ['Frontend'],
    'Sass': ['Frontend'],
    'Less': ['Frontend'],
    'Stylus': ['Frontend'],
    'PostCSS': ['Frontend'],
    'Tailwind CSS': ['Frontend'],
    'Bootstrap': ['Frontend'],
    'Material-UI': ['Frontend'],
    'Ant Design': ['Frontend'],
    'Chakra UI': ['Frontend'],
    'Semantic UI': ['Frontend'],
    'Foundation': ['Frontend'],
    'Bulma': ['Frontend'],
    'Materialize': ['Frontend'],
    'Vuetify': ['Frontend'],
    'PrimeNg': ['Frontend'],
    'Angular Material': ['Frontend'],
    'Angular Material ': ['Frontend'],
    'Material Design for Angular': ['Frontend'],
    'Kendo UI': ['Frontend'],
    'D3.js': ['Frontend', 'AI & Data'], # Data Visualization
    'three.js': ['Frontend', 'Game'], # 3D Graphics
    'Chart.js': ['Frontend', 'AI & Data'],
    'Highcharts': ['Frontend', 'AI & Data'],
    'Leaflet': ['Frontend'], # Maps
    'Mapbox': ['Frontend'], # Maps
    'Plotly.js': ['Frontend', 'AI & Data'],
    'Animate.css': ['Frontend'],
    'Animate.css ': ['Frontend'], # Trailing space variant
    'Aurelia': ['Frontend'],
    'Polymer': ['Frontend'],
    'Quasar Framework': ['Frontend'],
    'Bootstrap Vue': ['Frontend'],
    'Semantic UI React': ['Frontend'],
    'VuePress': ['Frontend', 'etc'],
    'React.js Boilerplate': ['Frontend'],
    'React Hot Loader': ['Frontend', 'DevOps'],
    'reactstrap': ['Frontend'],
    'Normalize.css': ['Frontend'],
    'Vue Native': ['Frontend', 'Game'],
    'Docusaurus': ['Frontend', 'etc'],
    'GLSL': ['Game', 'Frontend'],
    'MooTools': ['Frontend'],
    'YUI Library': ['Frontend'],

    # Backend Frameworks & Libraries
    'Node.js': ['Backend'],
    'ExpressJS': ['Backend'],
    'Django': ['Backend'],
    'Flask': ['Backend'],
    'Spring': ['Backend'],
    'Spring Boot': ['Backend'],
    'Spring Framework': ['Backend'],
    'Rails': ['Backend'],
    'Laravel': ['Backend'],
    'ASP.NET': ['Backend'],
    'ASP.NET Core': ['Backend'],
    'FastAPI': ['Backend'],
    'NestJS': ['Backend'],
    'Koa': ['Backend'],
    'AdonisJS': ['Backend'],
    'Phoenix Framework': ['Backend'],
    'Symfony': ['Backend'],
    'CodeIgniter': ['Backend'],
    'CakePHP': ['Backend'],
    'Yii': ['Backend'],
    'Lumen': ['Backend'],
    'Sinatra': ['Backend'],
    'Dropwizard': ['Backend'],
    'Play': ['Backend'], # Play Framework for Java/Scala
    'Hibernate': ['Backend'],
    'SQLAlchemy': ['Backend'],
    'Mongoose': ['Backend'],
    'Sequelize': ['Backend'],
    'TypeORM': ['Backend'],
    'Prisma': ['Backend'],
    'Entity Framework': ['Backend'],
    'Gunicorn': ['Backend'],
    'uWSGI': ['Backend'],
    'PM2': ['Backend'],
    'Celery': ['Backend', 'DevOps'],
    'Socket.IO': ['Backend', 'Frontend'],
    'GraphQL': ['Backend', 'Frontend'],
    'Apollo': ['Backend', 'Frontend'],
    'gRPC': ['Backend'],
    'Fastify': ['Backend'],
    'Gin Gonic': ['Backend'],
    'Apache Tomcat': ['Backend'],
    'Microsoft IIS': ['Backend', 'DevOps'],
    'OpenResty': ['Backend', 'DevOps'],
    'LiteSpeed': ['Backend', 'DevOps'],
    'Akka': ['Backend'],
    'Erlang': ['Backend'],
    'ActiveMQ': ['Backend', 'DevOps'],
    'Sidekiq': ['Backend', 'DevOps'],
    'Passenger': ['Backend', 'DevOps'],
    'Puma': ['Backend', 'DevOps'],
    'Spring Data': ['Backend'],
    'Spring Security': ['Backend', 'Security'],
    'Spring MVC': ['Backend'],
    'ws': ['Backend', 'Frontend'],
    'Tornado': ['Backend'],
    'Thymeleaf': ['Backend', 'Frontend'],
    'JHipster': ['Backend', 'Frontend', 'DevOps'],
    'MyBatis': ['Backend'],
    'Micronaut Framework': ['Backend'],
    'FeathersJS': ['Backend'],
    'Sails.js': ['Backend'],
    'LoopBack': ['Backend'],
    'Grails': ['Backend'],
    'Cowboy': ['Backend'],
    'Dapper': ['Backend'],
    'Quarkus': ['Backend'],
    'Netty': ['Backend'],
    'Vert.x': ['Backend'],
    'Knex.js': ['Backend'],
    'Doctrine 2': ['Backend'],
    'Zend Framework': ['Backend'],

    # AI & Data
    'TensorFlow': ['AI & Data'],
    'PyTorch': ['AI & Data'],
    'Keras': ['AI & Data'],
    'scikit-learn': ['AI & Data'],
    'Pandas': ['AI & Data'],
    'NumPy': ['AI & Data'],
    'SciPy': ['AI & Data'],
    'Jupyter': ['AI & Data', 'DevOps'],
    'Apache Spark': ['AI & Data'],
    'Hadoop': ['AI & Data'],
    'Kafka': ['AI & Data', 'Backend', 'DevOps'],
    'RabbitMQ': ['Backend', 'DevOps'],
    'Apache Flink': ['AI & Data'],
    'Apache Beam': ['AI & Data'],
    'OpenCV': ['AI & Data'],
    'Matplotlib': ['AI & Data'],
    'Databricks': ['AI & Data', 'DevOps'],
    'Snowflake': ['AI & Data', 'Backend'],
    'Google BigQuery': ['AI & Data', 'Backend'],
    'Amazon Redshift': ['AI & Data', 'Backend'],
    'LangChain': ['AI & Data', 'Embedding'],
    'SpaCy': ['AI & Data'],
    'Airflow': ['AI & Data', 'DevOps'],
    'Kubeflow': ['AI & Data', 'DevOps'],
    'MLflow': ['AI & Data', 'DevOps'],
    'dbt': ['AI & Data', 'Backend'],
    'Tableau': ['AI & Data'],
    'Power BI': ['AI & Data'],
    'Looker': ['AI & Data'],
    'Superset': ['AI & Data'],
    'Metabase': ['AI & Data'],
    'Streamlit': ['AI & Data', 'Frontend'],
    'Dash': ['AI & Data', 'Frontend'],
    'Amazon Kinesis': ['AI & Data', 'DevOps'],
    'Amazon Athena': ['AI & Data', 'Backend'],
    'Presto': ['AI & Data', 'Backend'],
    'AWS Glue': ['AI & Data', 'DevOps'],
    'Amazon EMR': ['AI & Data', 'DevOps'],
    'Druid': ['AI & Data', 'Backend'],
    'Apache NiFi': ['AI & Data', 'DevOps'],
    'HBase': ['AI & Data', 'Backend'],
    'Apache Hive': ['AI & Data'],
    'Kafka Streams': ['AI & Data', 'Backend'],
    'Dialogflow': ['AI & Data'],
    'PySpark': ['AI & Data'],
    'Apache Storm': ['AI & Data'],
    'Aerospike': ['AI & Data', 'Backend'],
    'TensorFlow.js': ['AI & Data', 'Frontend'],
    'Google Cloud Dataflow': ['AI & Data', 'DevOps'],
    'Avro': ['AI & Data', 'Backend'],
    'Confluent': ['AI & Data', 'Backend', 'DevOps'],
    'Amazon SageMaker': ['AI & Data'],
    'Amazon Quicksight': ['AI & Data'],
    'MATLAB': ['AI & Data'],
    'IPython': ['AI & Data'],
    'Torch': ['AI & Data'],
    'scikit-image': ['AI & Data'],
    'Talend': ['AI & Data'],
    'Apache Zeppelin': ['AI & Data'],
    'Chartio': ['AI & Data'],
    'Redash': ['AI & Data'],
    'Microsoft Bot Framework': ['AI & Data', 'Backend'],
    'PowerBI': ['AI & Data'], # Alias for Power BI
    'Data Studio': ['AI & Data'], # Google
    'Azure Machine Learning': ['AI & Data'],

    # DevOps
    'Docker': ['DevOps'],
    'Kubernetes': ['DevOps'],
    'Jenkins': ['DevOps'],
    'GitLab CI': ['DevOps'],
    'GitHub Actions': ['DevOps'],
    'CircleCI': ['DevOps'],
    'Travis CI': ['DevOps'],
    'Ansible': ['DevOps'],
    'Terraform': ['DevOps'],
    'Pulumi': ['DevOps'],
    'Chef': ['DevOps'],
    'Puppet Labs': ['DevOps'],
    'Vagrant': ['DevOps'],
    'Prometheus': ['DevOps'],
    'Grafana': ['DevOps'],
    'Datadog': ['DevOps', 'AI & Data'],
    'New Relic': ['DevOps'],
    'Splunk': ['DevOps', 'Security'],
    'ELK': ['DevOps', 'AI & Data'], # Elasticsearch, Logstash, Kibana
    'Elasticsearch': ['DevOps', 'Backend', 'AI & Data'],
    'Logstash': ['DevOps', 'AI & Data'],
    'Kibana': ['DevOps', 'AI & Data'],
    'Fluentd': ['DevOps'],
    'Jaeger': ['DevOps'],
    'Istio': ['DevOps'],
    'Envoy': ['DevOps'],
    'Consul': ['DevOps'],
    'NGINX': ['Backend', 'DevOps'],
    'Apache HTTP Server': ['Backend', 'DevOps'],
    'HAProxy': ['Backend', 'DevOps'],
    'Traefik': ['DevOps'],
    'Heroku': ['DevOps'],
    'Vercel': ['DevOps', 'Frontend'],
    'Netlify': ['DevOps', 'Frontend'],
    'AWS': ['DevOps', 'Backend', 'AI & Data'],
    'Amazon Web Services (AWS)': ['DevOps', 'Backend', 'AI & Data'],
    'Microsoft Azure': ['DevOps', 'Backend', 'AI & Data'],
    'Google Cloud Platform': ['DevOps', 'Backend', 'AI & Data'],
    'DigitalOcean': ['DevOps', 'Backend'],
    'Linux': ['DevOps', 'Backend'],
    'Ubuntu': ['DevOps', 'Backend'],
    'CentOS': ['DevOps', 'Backend'],
    'Debian': ['DevOps', 'Backend'],
    'Alpine Linux': ['DevOps'],
    'Serverless': ['DevOps', 'Backend'],
    'AWS Lambda': ['DevOps', 'Backend'],
    'Google Cloud Functions': ['DevOps', 'Backend'],
    'Azure Functions': ['DevOps', 'Backend'],
    'Docker Compose': ['DevOps'],
    'Amazon CloudFront': ['DevOps', 'Backend'],
    'GitHub Pages': ['DevOps', 'Frontend'],
    'Amazon Route 53': ['DevOps'],
    'Amazon EC2 Container Service': ['DevOps'],
    'AWS Elastic Load Balancing (ELB)': ['DevOps'],
    'Amazon CloudWatch': ['DevOps'],
    'Google App Engine': ['DevOps', 'Backend'],
    'Varnish': ['Backend', 'DevOps'],
    'Azure DevOps': ['DevOps'],
    'AWS Elastic Beanstalk': ['DevOps', 'Backend'],
    'Red Hat OpenShift': ['DevOps'],
    'AWS CloudFormation': ['DevOps'],
    'Azure Pipelines': ['DevOps'],
    'Amazon VPC': ['DevOps'],
    'Rancher': ['DevOps'],
    'Helm': ['DevOps'],
    'TeamCity': ['DevOps'],
    'Terraform Registry': ['DevOps'],
    'AWS IAM': ['DevOps', 'Security'],
    'Google Kubernetes Engine': ['DevOps'],
    'Kong': ['Backend', 'DevOps'],
    'Codeship': ['DevOps'],
    'OpenStack': ['DevOps'],
    'Nagios': ['DevOps'],
    'Docker Swarm': ['DevOps'],
    'Plesk': ['DevOps'],
    'pre-commit': ['DevOps'],
    'Zabbix': ['DevOps'],
    'Fastly': ['DevOps'],
    'Linode': ['DevOps'],
    'Lerna': ['DevOps'],
    'AWS CodePipeline': ['DevOps'],
    'Drone.io': ['DevOps'],
    'Portainer': ['DevOps'],
    'Argo': ['DevOps'],
    'Packer': ['DevOps'],
    'Fedora': ['DevOps', 'etc'],
    'AWS Fargate': ['DevOps'],
    'Arch Linux': ['DevOps', 'etc'],
    'Homebrew': ['DevOps', 'etc'],
    'AWS CodeCommit': ['DevOps'],
    'Google Cloud Build': ['DevOps'],
    'Bamboo': ['DevOps'],
    'AWS CodeDeploy': ['DevOps'],
    'Eureka': ['DevOps', 'Backend'],
    'AWS CodeBuild': ['DevOps'],
    'Sonatype Nexus': ['DevOps'],
    'Docker Machine': ['DevOps'],
    'Octopus Deploy': ['DevOps'],
    'Salt': ['DevOps'],
    'NATS': ['Backend', 'DevOps'],
    'AppDynamics': ['DevOps'],
    'Loki': ['DevOps'],
    'ngrok': ['DevOps', 'etc'],
    'Fabric': ['DevOps'],
    'Apigee': ['Backend', 'DevOps'],
    'Sauce Labs': ['DevOps'],
    'Azure Websites': ['DevOps', 'Backend'],
    'Flyway': ['DevOps', 'Backend'],
    'hub': ['DevOps', 'etc'],
    'Graphite': ['DevOps'],
    'Zuul': ['DevOps', 'Backend'],
    'Gitea': ['DevOps', 'etc'],
    'JFrog Artifactory': ['DevOps'],
    'Buddy': ['DevOps'],
    'Proxmox VE': ['DevOps'],
    'Amazon Elasticsearch Service': ['DevOps', 'AI & Data', 'Backend'],
    'Azure Data Factory': ['AI & Data', 'DevOps'],
    'Azure App Service': ['DevOps', 'Backend'],
    'Stackdriver': ['DevOps'],
    'Caddy': ['Backend', 'DevOps'],
    'Azure Application Insights': ['DevOps'],
    'Concourse': ['DevOps'],
    'wercker': ['DevOps'],
    'Telegraf': ['DevOps'],
    'AWS Step Functions': ['DevOps', 'Backend'],
    'Netdata': ['DevOps'],
    'Loggly': ['DevOps'],
    'Nomad': ['DevOps'],
    'Amazon ECR': ['DevOps'],
    'Spinnaker': ['DevOps'],
    'LogRocket': ['DevOps', 'Frontend'],
    'Gatling': ['DevOps'],
    'OpsGenie': ['DevOps'],
    'Splunk Cloud': ['DevOps', 'Security'],
    'GoCD': ['DevOps'],
    'boot2docker': ['DevOps'],
    'CoreOS': ['DevOps'],
    'Rundeck': ['DevOps'],
    'Hystrix': ['Backend', 'DevOps'],
    'SonarLint': ['DevOps'],
    'Cloud Foundry': ['DevOps'],
    'k6': ['DevOps'],
    'Render': ['DevOps'],
    'Locust': ['DevOps'],
    'ESLint': ['Frontend', 'DevOps'],
    'Yarn': ['Frontend', 'DevOps'],
    'Matomo': ['AI & Data', 'etc'],
    'Amazon EKS': ['DevOps'],
    'Bazel': ['DevOps'],
    'Laravel Forge': ['DevOps'],
    'Docker Hub': ['DevOps'],
    'Jenkins X': ['DevOps'],
    'Lighthouse': ['Frontend', 'DevOps'],
    'Mercurial': ['DevOps'],
    'OpenVPN': ['Security', 'DevOps'],
    'Sumo Logic': ['DevOps', 'Security'],
    'GitHub Enterprise': ['DevOps', 'etc'],
    'Laravel Homestead': ['DevOps'],
    'Windows Server': ['DevOps', 'Backend'],

    # Embedding
    'pgvector': ['Embedding', 'AI & Data', 'Backend'],
    'CUDA': ['AI & Data', 'Game', 'Embedding'],
    'Raspberry Pi': ['Embedding', 'etc'],

    # Game
    'Unity': ['Game'],
    'Unreal Engine': ['Game'],
    'Blender': ['Game', 'etc'], # Also a design tool
    'Android Studio': ['Game', 'Frontend', 'etc'],
    'Xcode': ['Game', 'Frontend', 'etc'],
    'FFMPEG': ['Game', 'AI & Data', 'etc'],

    # Security
    'OpenSSL': ['Security', 'Backend', 'DevOps'],
    'Vault': ['Security', 'DevOps'],
    'Keycloak': ['Security', 'Backend'],
    'Auth0': ['Security', 'Backend', 'Frontend'],
    'Okta': ['Security', 'DevOps'],
    'OAuth2': ['Security', 'Backend'],
    'JSON Web Token': ['Security', 'Backend', 'Frontend'],
    'Snyk': ['Security', 'DevOps'],
    'SonarQube': ['DevOps', 'Security'],
    'Kali Linux': ['Security', 'DevOps'],
    'Let\'s Encrypt': ['Security', 'DevOps'],
    'AWS IAM': ['DevOps', 'Security'],
    'Amazon Cognito': ['Security', 'Backend'],
    'Firebase Authentication': ['Security', 'Backend'],
    'Azure Active Directory': ['Security', 'DevOps'],
    'Passport': ['Backend', 'Security'],
    'Devise': ['Backend', 'Security'],
    '1Password': ['etc', 'Security'],
    'bitwarden': ['etc', 'Security'],
    'LastPass': ['etc', 'Security'],
    'Incapsula': ['Security', 'DevOps'],

    # Databases (mostly Backend, but some have other uses)
    'PostgreSQL': ['Backend', 'AI & Data'],
    'MySQL': ['Backend'],
    'MariaDB': ['Backend'],
    'SQLite': ['Backend', 'Frontend'], # Mobile/local
    'Microsoft SQL Server': ['Backend'],
    'Oracle': ['Backend'],
    'MongoDB': ['Backend'],
    'Redis': ['Backend', 'DevOps'],
    'Cassandra': ['Backend', 'AI & Data'],
    'Amazon DynamoDB': ['Backend'],
    'Google Cloud Firestore': ['Backend'],
    'CouchDB': ['Backend'],
    'Neo4j': ['Backend', 'AI & Data'], # Graph DB
    'InfluxDB': ['DevOps', 'AI & Data'], # Time series
    'TimescaleDB': ['DevOps', 'AI & Data', 'Backend'],
    'ArangoDB': ['Backend', 'AI & Data'],
    'RethinkDB': ['Backend'],
    'CockroachDB': ['Backend'],
    'Amazon RDS': ['Backend', 'DevOps'],
    'Amazon Aurora': ['Backend', 'DevOps'],
    'Azure Cosmos DB': ['Backend', 'DevOps'],
    'Solr': ['Backend', 'AI & Data'],
    'Amazon RDS for PostgreSQL': ['Backend', 'DevOps'],
    'H2 Database': ['Backend'],
    'Google Cloud SQL': ['Backend', 'DevOps'],
    'Azure SQL Database': ['Backend', 'DevOps'],
    'HBase': ['AI & Data', 'Backend'],
    'Clickhouse': ['AI & Data', 'Backend'],
    'Hazelcast': ['Backend'],
    'Ehcache': ['Backend'],
    'PostGIS': ['Backend', 'AI & Data'],
    'Supabase': ['Backend', 'DevOps', 'Frontend'],
    'etcd': ['DevOps', 'Backend'],
    'Realm': ['Backend', 'Frontend'],
    'IBM DB2': ['Backend'],
    'Google Cloud Bigtable': ['AI & Data', 'Backend'],
    'Cloud DB for Mysql': ['Backend', 'DevOps'],
    'Couchbase': ['Backend'],
    'Memcached': ['Backend', 'DevOps'],
    'Google Cloud Datastore': ['Backend'],
    'HSQLDB': ['Backend'],

    # etc (Collaboration, Design, PM, Misc)
    'Slack': ['etc'],
    'Jira': ['etc'],
    'Confluence': ['etc'],
    'Trello': ['etc'],
    'Asana': ['etc'],
    'Notion': ['etc'],
    'Miro': ['etc'],
    'Figma': ['etc', 'Frontend'],
    'Sketch': ['etc', 'Frontend'],
    'Adobe XD': ['etc', 'Frontend'],
    'Zeplin': ['etc', 'Frontend'],
    'InVision': ['etc', 'Frontend'],
    'GitHub': ['DevOps', 'etc'],
    'GitLab': ['DevOps', 'etc'],
    'Bitbucket': ['DevOps', 'etc'],
    'Git': ['DevOps', 'etc'],
    'SVN (Subversion)': ['DevOps', 'etc'],
    'Google Drive': ['etc'],
    'Google Docs': ['etc'],
    'Google Sheets': ['etc'],
    'Dropbox': ['etc'],
    'Microsoft Teams': ['etc'],
    'Zoom': ['etc'],
    'Skype': ['etc'],
    'Gmail': ['etc'],
    'Google Workspace': ['etc'],
    'Microsoft 365': ['etc'],
    'WordPress': ['Frontend', 'Backend', 'etc'],
    'Shopify': ['Frontend', 'Backend', 'etc'],
    'WooCommerce': ['Frontend', 'Backend', 'etc'],
    'Squarespace': ['etc'],
    'Wix': ['etc'],
    'Visual Studio Code': ['etc'],
    'IntelliJ IDEA': ['etc'],
    'PyCharm': ['etc'],
    'WebStorm': ['etc'],
    'GoLand': ['etc'],
    'CLion': ['etc'],
    'RubyMine': ['etc'],
    'JetBrains Rider': ['etc'],
    'Visual Studio': ['etc'],
    'Sublime Text': ['etc'],
    'Atom': ['etc'],
    'Vim': ['etc'],
    'Emacs': ['etc'],
    'Postman': ['etc', 'Backend', 'DevOps'],
    'Insomnia REST Client': ['etc', 'Backend', 'DevOps'],
    'Swagger UI': ['etc', 'Backend'],
    'Markdown': ['etc'],
    'JSON': ['Frontend', 'Backend', 'AI & Data', 'DevOps', 'Embedding', 'Game', 'Security', 'etc'],
    'YAML': ['DevOps', 'Backend', 'etc'],
    'XML': ['Backend', 'etc'],
    'ChatGPT': ['AI & Data', 'etc'],
    'Babel': ['Frontend', 'DevOps'],
    'Gradle': ['DevOps', 'Backend', 'Game'],
    'Android SDK': ['Frontend', 'Game'],
    'Mailchimp': ['etc'],
    'PayPal': ['Backend', 'etc'],
    'Stripe': ['Backend', 'etc'],
    'Notepad++': ['etc'],
    'Selenium': ['DevOps', 'Frontend'],
    'PhpStorm': ['etc'],
    'Sentry': ['DevOps', 'Backend', 'Frontend'],
    'gulp': ['Frontend', 'DevOps'],
    'Twilio': ['Backend', 'etc'],
    'SourceTree': ['etc'],
    'HubSpot': ['etc'],
    'Amazon SES': ['Backend', 'DevOps'],
    'Jest': ['Frontend', 'DevOps'],
    'Twilio SendGrid': ['Backend', 'etc'],
    'Drupal': ['Frontend', 'Backend', 'etc'],
    'Grunt': ['Frontend', 'DevOps'],
    'Zendesk': ['etc'],
    'Mailgun': ['Backend', 'etc'],
    'PyPI': ['DevOps', 'Backend'],
    'RequireJS': ['Frontend'],
    'Mocha': ['Frontend', 'DevOps'],
    'Bower': ['Frontend', 'DevOps'],
    'Mixpanel': ['AI & Data', 'etc'],
    'Prettier': ['Frontend', 'DevOps', 'etc'],
    'Handlebars.js': ['Frontend'],
    'Intercom': ['etc'],
    'Lodash': ['Frontend'],
    'NuGet': ['DevOps', 'Backend'],
    'RubyGems': ['DevOps', 'Backend'],
    'Slick': ['Frontend'],
    'Modernizr': ['Frontend'],
    'JUnit': ['Backend', 'DevOps'],
    'Logback': ['Backend', 'DevOps'],
    'Mandrill': ['Backend', 'etc'],
    'Moment.js': ['Frontend'],
    'axios': ['Frontend', 'Backend'],
    'Chai': ['Frontend', 'Backend', 'DevOps'],
    'Jasmine': ['Frontend', 'Backend', 'DevOps'],
    'AddThis': ['etc'],
    'Karma': ['Frontend', 'DevOps'],
    'Cypress': ['Frontend', 'DevOps'],
    'Apache Maven': ['DevOps', 'Backend'],
    'CoffeeScript': ['Frontend'],
    'Dotenv': ['Backend', 'DevOps'],
    'Eclipse': ['etc'],
    'fancybox': ['Frontend'],
    'Amazon SQS': ['Backend', 'DevOps'],
    'RxJS': ['Frontend', 'Backend'],
    'Optimizely': ['Frontend', 'etc'],
    'BrowserStack': ['DevOps', 'Frontend'],
    'pytest': ['Backend', 'DevOps'],
    'CMake': ['DevOps', 'Game', 'Backend'],
    'SLF4J': ['Backend', 'DevOps'],
    'Protobuf': ['Backend', 'AI & Data'],
    'Salesforce Sales Cloud': ['etc'],
    'Pingdom': ['DevOps'],
    'Autoprefixer': ['Frontend', 'DevOps'],
    'Mockito': ['Backend', 'DevOps'],
    'Typekit': ['Frontend', 'etc'],
    'Segment': ['AI & Data', 'etc'],
    'RSpec': ['Backend', 'DevOps'],
    'Django REST framework': ['Backend'],
    'css-loader': ['Frontend', 'DevOps'],
    'TSLint': ['Frontend', 'DevOps'],
    'SinonJS': ['Frontend', 'DevOps'],
    'Magento': ['Frontend', 'Backend', 'etc'],
    'Meteor': ['Frontend', 'Backend'],
    'Adobe Photoshop': ['etc'],
    'nodemon': ['DevOps', 'Backend', 'Frontend'],
    'CocoaPods': ['DevOps', 'Frontend'],
    'Log4j': ['Backend', 'DevOps'],
    'Jekyll': ['Frontend', 'etc'],
    'Smarty': ['Frontend'],
    'TrackJS': ['Frontend', 'DevOps'],
    'Codecov': ['DevOps'],
    'xUnit': ['Backend', 'DevOps'],
    'iOS': ['Frontend', 'Game'],
    'PHPUnit': ['Backend', 'DevOps'],
    'Yeoman': ['Frontend', 'DevOps'],
    'Google Cloud Storage': ['Backend', 'DevOps'],
    'Discord': ['etc'],
    'AdRoll': ['etc'],
    'Namecheap': ['etc'],
    'Disqus': ['etc'],
    'Acquia': ['DevOps'],
    'Browserify': ['Frontend', 'DevOps'],
    'Rollbar': ['DevOps', 'Backend', 'Frontend'],
    'Select2': ['Frontend'],
    'Jinja': ['Backend', 'Frontend'],
    'Testify': ['Backend', 'DevOps'],
    'Mustache': ['Frontend', 'Backend'],
    'Zapier': ['etc'],
    'Protractor': ['Frontend', 'DevOps'],
    'Google Cloud DNS': ['DevOps'],
    'Crazy Egg': ['etc'],
    'Underscore': ['Frontend'],
    'guava': ['Backend'],
    'rollup': ['Frontend', 'DevOps'],
    'Moq': ['Backend', 'DevOps'],
    'Amazon SNS': ['Backend', 'DevOps'],
    'Adobe Illustrator': ['etc'],
    'Algolia': ['Frontend', 'Backend', 'AI & Data'],
    'Hugo': ['Frontend', 'etc'],
    'DNS Made Easy': ['DevOps'],
    'Serilog': ['Backend', 'DevOps'],
    'Amazon ElastiCache': ['Backend', 'DevOps'],
    'Cucumber': ['DevOps'],
    'MaxCDN': ['DevOps'],
    'HipChat': ['etc'],
    'Capistrano': ['DevOps'],
    'Arduino': ['Embedding'],
    'PhantomJS': ['Frontend', 'DevOps'],
    'Prototype': ['Frontend'],
    'Akamai': ['DevOps'],
    'Marketo': ['etc'],
    'Azure Storage': ['Backend', 'DevOps'],
    'Coveralls': ['DevOps'],
    'Zoho Mail': ['etc'],
    'Enzyme': ['Frontend', 'DevOps'],
    'Vite': ['Frontend', 'DevOps'],
    'SuperTest': ['Backend', 'DevOps'],
    'Piwik': ['AI & Data', 'etc'],
    'Gherkin': ['DevOps'],
    'Windows': ['etc'],
    'TestFlight': ['DevOps', 'Frontend', 'Game'],
    'Airtable': ['etc'],
    'Pusher': ['Backend', 'Frontend'],
    'React Redux': ['Frontend'],
    'NUnit': ['Backend', 'DevOps'],
    'React Navigation': ['Frontend'],
    'Gravity Forms': ['etc'],
    'jsdom': ['Frontend', 'DevOps'],
    'Stylelint': ['Frontend', 'DevOps'],
    'Quantcast': ['etc'],
    'Composer': ['DevOps', 'Backend'],
    'Joomla!': ['Frontend', 'Backend', 'etc'],
    'PagerDuty': ['DevOps'],
    'RuboCop': ['DevOps', 'Backend'],
    'Bugsnag': ['DevOps'],
    'Visual Website Optimizer': ['etc'],
    'Simple': ['etc'],
    'Hotjar': ['etc'],
    'MongoDB Atlas': ['Backend', 'DevOps'],
    'Crashlytics': ['DevOps', 'Frontend', 'Game'],
    'SignalR': ['Backend', 'Frontend'],
    'Dyn': ['DevOps'],
    'Contentful': ['Backend', 'Frontend', 'etc'],
    'GitKraken': ['etc'],
    'Webflow': ['Frontend', 'etc'],
    'Puppeteer': ['Frontend', 'DevOps'],
    'JSHint': ['Frontend', 'DevOps'],
    'NetBeans IDE': ['etc'],
    'Elementor': ['Frontend', 'etc'],
    'Amplitude': ['AI & Data', 'etc'],
    'Apache Cordova': ['Frontend', 'Game'],
    'TestNG': ['Backend', 'DevOps'],
    'Balsamiq': ['etc'],
    'MSSQL': ['Backend'],
    'Bundler': ['DevOps', 'Backend'],
    'date-fns': ['Frontend'],
    'Sphinx': ['etc'],
    'Medium': ['etc'],
    'Google Chrome': ['etc'],
    'ClickUp': ['etc'],
    'Ionicons': ['Frontend'],
    'Material Design': ['Frontend'],
    'Neovim': ['etc'],
    'Telegram': ['etc'],
    'Salesforce': ['etc'],
    'DataTables': ['Frontend'],
    'Oracle PL/SQL': ['Backend'],
    'flake8': ['DevOps', 'Backend'],
    'Code Climate': ['DevOps'],
    'Graylog': ['DevOps'],
    'Minio': ['DevOps', 'Backend'],
    'PhoneGap': ['Frontend', 'Game'],
    'Blazor': ['Frontend', 'Backend'],
    'AWS Cloud9': ['etc'],
    'Liquibase': ['DevOps', 'Backend'],
    'OpenLayers': ['Frontend'],
    'Cloudinary': ['Frontend', 'etc'],
    'Amazon EBS': ['DevOps'],
    'Microsoft Excel': ['etc'],
    'Buffer': ['etc'],
    'DBeaver': ['etc'],
    'Appium': ['DevOps', 'Frontend', 'Game'],
    'Basecamp': ['etc'],
    'DataGrip': ['etc'],
    'MQTT': ['Backend', 'Embedding'],
    'Clicky': ['etc'],
    'fastlane': ['DevOps', 'Frontend', 'Game'],
    'UIkIt': ['Frontend'],
    'AWS Amplify': ['Frontend', 'Backend', 'DevOps'],
    'Prism': ['Frontend'],
    'Brackets': ['etc'],
    'Red Hat Codeready Workspaces': ['etc'],
    'VMware vSphere': ['DevOps'],
    'Pivotal Tracker': ['etc'],
    'Parcel': ['Frontend', 'DevOps'],
    'Capybara': ['Frontend', 'DevOps'],
    'Heap': ['AI & Data', 'etc'],
    'Redmine': ['etc'],
    'QUnit': ['Frontend', 'DevOps'],
    'Papertrail': ['DevOps'],
    'DB': ['Backend'],
    'Mattermost': ['etc'],
    'Google Meet': ['etc'],
    'pip': ['DevOps', 'Backend', 'AI & Data'],
    'Pylint': ['DevOps', 'Backend', 'AI & Data'],
    'Adobe Experience Manager': ['etc'],
    'ScalaTest': ['Backend', 'DevOps'],
    'React Storybook': ['Frontend', 'DevOps'],
    'Flux': ['Frontend'],
    'Azure Service Bus': ['Backend', 'DevOps'],
    'Netlify CMS': ['etc'],
    'GoDaddy': ['etc'],
    'Qt': ['Frontend', 'Game', 'Embedding'],
    'macOS': ['etc'],
    'Material Design Lite': ['Frontend'],
    'Chartbeat': ['etc'],
    'Octokit': ['Backend', 'DevOps'],
    'MySQL WorkBench': ['etc'],
    'jsdoc': ['Frontend', 'etc'],
    'CodeMirror': ['Frontend'],
    'Braintree': ['Backend', 'etc'],
    'HAML': ['Frontend'],
    'Dataform': ['AI & Data', 'Backend'],
    'Guzzle': ['Backend'],
    'Heroku Postgres': ['Backend', 'DevOps'],
    'Formik': ['Frontend'],
    'Owin': ['Backend'],
    'Unicorn': ['Backend', 'DevOps'],
    'tawk.to': ['etc'],
    'Microsoft SQL Server Management Studio': ['etc'],
    'RestSharp': ['Backend'],
    'UglifyJS': ['Frontend', 'DevOps'],
    'RocketChat': ['etc'],
    'Spock Framework': ['Backend', 'DevOps'],
    'Istanbul': ['Frontend', 'DevOps'],
    'WebdriverIO': ['Frontend', 'DevOps'],
    'hapi': ['Backend'],
    'EJS': ['Frontend'],
    'Cloud Functions for Firebase': ['Backend', 'DevOps'],
    'Jitsi': ['etc'],
    'Vue CLI': ['Frontend', 'DevOps'],
    'Pillow': ['AI & Data', 'Backend'],
    'WhatsApp': ['etc'],
    'MongoLab': ['Backend', 'DevOps'],
    'RStudio': ['etc'],
    'Facebook Ads': ['etc'],
    'Framer': ['Frontend', 'etc'],
    'Robot Framework': ['DevOps'],
    'Codacy': ['DevOps'],
    'OneSignal': ['Frontend', 'Game', 'etc'],
    'Jetty': ['Backend'],
    'cURL': ['DevOps', 'Backend', 'etc'],
    'WebRTC': ['Frontend', 'Backend'],
    'LiveReload': ['Frontend', 'DevOps'],
    'FindBugs': ['DevOps', 'Backend'],
    'LiveChat': ['etc'],
    'Redash': ['AI & Data'],
    'Chartio': ['AI & Data'],
    'clipboard.js': ['Frontend'],
    'Google Ads': ['etc'],
    'Deno': ['Backend', 'Frontend'],
    'Lottie': ['Frontend'],
    'drawio': ['etc'],
    'ZeroMQ': ['Backend'],
    'GlassFish': ['Backend'],
    'AWK': ['DevOps'],
    'Nix': ['DevOps'],
    'Immutable.js': ['Frontend'],
    'Windows 10': ['etc'],
    'Oh My ZSH': ['etc'],
    'Microsoft SharePoint': ['etc'],
    'Bootstrap Studio': ['etc'],
    'KISSmetrics': ['etc'],
    'FreshDesk': ['etc'],
    'monday.com': ['etc'],
    'Pardot': ['etc'],
    'BigCommerce': ['etc'],
    'Apache JMeter': ['DevOps'],
    'JBoss': ['Backend'],
    'OpenCensus': ['DevOps'],
    'Bubble': ['etc'],
    'Azure Kubernetes Service': ['DevOps'],
    'iTerm2': ['etc'],
    'Hexo': ['Frontend', 'etc'],
    'LambdaTest': ['DevOps'],
    'Adobe InDesign': ['etc'],
    'Bitbucket Pipelines': ['DevOps'],
    'Bitrise': ['DevOps'],
    'Angular Universal': ['Frontend', 'Backend'],
    'Blogger': ['etc'],
    'Apache Mesos': ['DevOps'],
    'PrestaShop': ['etc'],
    'dbForge Studio for MySQL': ['etc'],
    'PubNub': ['Backend', 'Frontend'],
    'OpenStreetMap': ['etc'],
    'OVH': ['DevOps'],
    'i18next': ['Frontend'],
    'Nodemailer': ['Backend'],
    'StatsD': ['DevOps'],
    'Sequel Pro': ['etc'],
    'Azure Machine Learning': ['AI & Data'],
    'FullStory': ['etc'],
    'Phalcon': ['Backend'],
    'Postmark': ['Backend', 'etc'],
    'Q': ['Frontend', 'Backend'],
    'Apiary': ['etc'],
    'Twig': ['Frontend', 'Backend'],
    'Olark': ['etc'],
    'Echo': ['Backend'],
    'Zopim': ['etc'],
    'AutoFac': ['Backend'],
    'Capacitor': ['Frontend', 'Game'],
    'Gitbook': ['etc'],
    'Tower': ['etc'],
    'PHPStan': ['DevOps', 'Backend'],
    'Stream': ['Backend', 'etc'],
    'Phabricator': ['DevOps', 'etc'],
    'MongoDB Compass': ['etc'],
    'UserVoice': ['etc'],
    'ZenHub': ['etc'],
    'Rackspace Cloud Servers': ['DevOps'],
    'OpenCart': ['etc'],
    'imgix': ['Frontend', 'etc'],
    'Facebook Pixel': ['etc'],
    'Gitter': ['etc'],
    'Amazon LightSail': ['DevOps'],
    'Customer.io': ['etc'],
    'Linear': ['etc'],
    'TestCafe': ['Frontend', 'DevOps'],
    'Paw': ['etc'],
    'Hubot': ['DevOps', 'etc'],
    'Lucidchart': ['etc'],
    'Bootsnap': ['Backend', 'DevOps'],
    'ent': ['Backend'],
    'Google Cloud Run': ['DevOps', 'Backend'],
    'Discourse': ['etc'],
    'OneDrive': ['etc'],
    'XenForo': ['etc'],
    'Zsh (Z shell)': ['etc'],
    'Help Scout': ['etc'],
    'SendBird': ['Backend', 'Frontend'],
    'Nexmo': ['Backend', 'etc'],
    'Logentries': ['DevOps'],
    'ReSharper': ['etc'],
    'Calendly': ['etc'],
    'Make': ['DevOps'],
    'Google Analytics': ['etc'],
    'Stack Overflow': ['etc'],
    'CloudFlare': ['DevOps', 'Security'],
    'Amazon S3': ['DevOps', 'Backend'],
    'Google Fonts': ['Frontend'],
    'Amazon EC2': ['DevOps', 'Backend'],
    'Firebase': ['Backend', 'Frontend', 'DevOps'],
    'Webpack': ['Frontend', 'DevOps'],
    'Google Maps': ['Frontend'],
    'Font Awesome': ['Frontend'],
    'Google Tag Manager': ['etc'],
    'VirtualBox': ['DevOps', 'etc'],
    'Google AdSense': ['etc'],
    'Storybook': ['Frontend', 'DevOps'],
    'Amazon EKS': ['DevOps'],
    'Telegram ': ['etc'],
    'Ghost': ['etc'],
    'Anaconda': ['AI & Data', 'DevOps'],
    'Blockchain ': ['Backend', 'etc'],
    'OmniAuth': ['Backend', 'Security'],
    'TinyMCE': ['Frontend'],
    'Scrapy': ['AI & Data', 'Backend'],
    'Nextcloud': ['etc'],
    'Zoho CRM': ['etc'],
    'Testrail': ['etc'],
    'Gogs': ['DevOps', 'etc'],
    'Google Search Console': ['etc'],
    'ActionScript': ['Frontend', 'Game'],
    'Apache Traffic Server': ['DevOps', 'Backend'],
    'Recharts': ['Frontend'],
    'SumoMe': ['etc'],
    'react-testing-library': ['Frontend', 'DevOps'],
    'Microsoft Outlook': ['etc'],
    'NSQ': ['Backend', 'DevOps'],
    'Android Room': ['Frontend', 'Game'],
    'Sitefinity': ['etc'],
    'Box': ['etc'],
    'Sanity': ['Backend', 'Frontend', 'etc'],
    'Google': ['etc'],
    'GNU sed': ['DevOps'],
    'Vaadin': ['Frontend', 'Backend'],
    'Salesforce Marketing Cloud': ['etc'],
    'Sumo Logic': ['DevOps', 'Security'],
    'Ktor': ['Backend'],
}
